# Continuous Integration workflow
name: CI

# Run on all pushes and pull requests to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          
      - name: Install dependencies
        shell: bash -el {0}
        run: conda env create -f environment.yml
        
      - name: Lint with flake8
        shell: bash -el {0}
        run: |
          conda activate greeter-env
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
